name: dispatch_source_watcher
description: Listen to DispatchSource file events on iOS
version: 0.2.1
homepage: https://github.com/swiftllama/flutter-dispatch-source-watcher

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DispatchSourceWatcherPlugin
